name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: '        Startup ChromeDriver and Display in Ubuntu'
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          # TODO: need to download driver according to electron's version
          wget --directory-prefix=/tmp https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
          unzip -d /tmp/chromedriver /tmp/chromedriver_linux64.zip
          sudo chmod +x /tmp/chromedriver/chromedriver
          /tmp/chromedriver/chromedriver &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: '        Create COV_REPORT'
        run: |
          mkdir COV_REPORT
      - name: '        Tests'
        shell: bash
        env:
          DISPLAY: ':99'
        run: |
          npm ci
          npm run test:jest
      - name: '        Copy jest results'
        run: |
          cp coverage_jest/coverage-final.json COV_REPORT/coverage-final-jest.json
      - name: '        Tests - Mocha'
        run: npm run test:mocha
        shell: bash
        if: matrix.os == 'ubuntu-latest'
      - name: '        Copy mocha results'
        run: |
          cp coverage_jest/coverage-final.json COV_REPORT/coverage-final-mocha.json
        if: matrix.os == 'ubuntu-latest'
      - name: '        CodeCov'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: COV_REPORT/coverage-final-*.json
          name: codecov-${{ matrix.os }}
          verbose: true